import React, { useState, useEffect } from "react";
import { View, Text, StyleSheet, Image, ScrollView, TextInput, Dimensions, Keyboard, TouchableWithoutFeedback } from 'react-native';
import { Ionicons } from "@expo/vector-icons";
import { useTheme } from "../../ThemeProvider";


const { width, height } = Dimensions.get('window');

const PrivacyPolicyScreen = ({ navigation }) => {
    const { theme } = useTheme();
    const styles = createStyles(theme);


    return (
        <View style={styles.container}>
        <ScrollView style={styles.scorllContainer}>
            <Ionicons name="chevron-back" onPress={() => navigation.goBack()} size={getResponsiveFontSize(25)} color={theme.textColor} style={styles.backIcon}/>
            <Text style={styles.title}>Privacy Policy</Text>
            <Text style={styles.subtext}>Last updated: November 13, 2024</Text>

            <Text style={styles.paragraph}>
                This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
                information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </Text>

            <Text style={styles.paragraph}>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
                and use of information in accordance with this Privacy Policy.
            </Text>

            <Text style={styles.heading}>Interpretation and Definitions</Text>

            <Text style={styles.subheading}>Interpretation</Text>
            <Text style={styles.paragraph}>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The
                following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </Text>

            <Text style={styles.subheading}>Definitions</Text>
            <Text style={styles.paragraph}>
                For the purposes of this Privacy Policy:
            </Text>
            <View style={styles.list}>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Account:</Text> means a unique account created for You to access our Service or
                parts of our Service.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Affiliate:</Text> means an entity that controls, is controlled by or is under
                common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or
                other securities entitled to vote for election of directors or other managing authority.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Application:</Text> refers to LiftX, the software program provided by the Company.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Company:</Text> (referred to as either "the Company", "We", "Us" or "Our" in this
                Agreement) refers to LiftX.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Country:</Text> refers to: California, United States.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Device:</Text> means any device that can access the Service such as a computer, a
                cellphone, or a digital tablet.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Personal Data:</Text> is any information that relates to an identified or
                identifiable individual.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Service:</Text> refers to the Application.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Service Provider:</Text> means any natural or legal person who processes the data on
                behalf of the Company.
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>Usage Data:</Text> refers to data collected automatically, either generated by the
                use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </Text>
                <Text style={styles.listItem}>
                <Text style={styles.bold}>You:</Text> means the individual accessing or using the Service, or the company, or
                other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </Text>
            </View>

            {/* Collecting and Using Your Personal Data */}
            <View style={styles.section}>
                <Text style={styles.heading}>Collecting and Using Your Personal Data</Text>
                <Text style={styles.subheading}>Types of Data Collected</Text>
                <Text style={styles.paragraph}>
                <Text style={styles.bold}>Personal Data</Text>
                {"\n"}While using Our Service, We may ask You to provide Us with certain personally
                identifiable information that can be used to contact or identify You. Personally
                identifiable information may include, but is not limited to:
                </Text>
                <Text style={styles.listItem}>• Email address</Text>
                <Text style={styles.listItem}>• First name and last name</Text>
                <Text style={styles.listItem}>• Usage Data</Text>

                <Text style={styles.paragraph}>
                <Text style={styles.bold}>Usage Data</Text>
                {"\n"}Usage Data is collected automatically when using the Service. Usage Data may include
                information such as Your Device's Internet Protocol address (e.g. IP address),
                browser type, browser version, the pages of our Service that You visit, the time and
                date of Your visit, the time spent on those pages, unique device identifiers, and
                other diagnostic data.
                </Text>

                <Text style={styles.paragraph}>
                <Text style={styles.bold}>Information Collected while Using the Application</Text>
                {"\n"}While using Our Application, in order to provide features of Our Application, 
                We may collect, with Your prior permission: 
                {"\n"}• Pictures and other information from your Device's camera and photo library{"\n"}
                We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
                You can enable or disable access to this information at any time, through Your Device settings.
                </Text>
            </View>

            {/* Use of Your Personal Data */}
            <View style={styles.section}>
                <Text style={styles.subheading}>Use of Your Personal Data</Text>
                <Text style={styles.paragraph}>
                The Company may use Personal Data for the following purposes:
                </Text>
                <Text style={styles.listItem}>
                • To provide and maintain our Service, including to monitor the usage of our Service.
                </Text>
                <Text style={styles.listItem}>
                • To manage Your Account: to manage Your registration as a user of the Service. The
                Personal Data You provide can give You access to different functionalities of the
                Service that are available to You as a registered user.
                </Text>
                <Text style={styles.listItem}>
                • For the performance of a contract: the development, compliance, and undertaking of
                the purchase contract for the products, items, or services You have purchased or of
                any other contract with Us through the Service.
                </Text>
                <Text style={styles.listItem}>
                • To contact You: To contact You by email, telephone calls, SMS, or other equivalent
                forms of electronic communication regarding updates, products, services, and
                security updates, when necessary or reasonable for their implementation.
                </Text>
                <Text style={styles.listItem}>
                • To provide You with news, special offers and general information about other goods, services 
                and events which we offer that are similar to those that you have already purchased or enquired 
                about unless You have opted not to receive such information.
                </Text>
                <Text style={styles.listItem}>
                • To manage Your requests: To attend and manage Your requests to Us.
                </Text>
                <Text style={styles.listItem}>
                • For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, 
                restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, 
                whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which 
                Personal Data held by Us about our Service users is among the assets transferred.
                </Text>
                <Text style={styles.listItem}>
                • For other purposes: We may use Your information for other purposes, such as data analysis, identifying 
                usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our 
                Service, products, services, marketing and your experience.
                </Text>
                <Text style={styles.paragraph}>We may share Your personal information in the following situations:</Text>
                <Text style={styles.listItem}>
                • With Service Providers: We may share Your personal information with Service Providers to monitor and 
                analyze the use of our Service, to contact You.
                </Text>
                <Text style={styles.listItem}>
                • For business transfers: We may share or transfer Your personal information in connection with, or during 
                negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our 
                business to another company.
                </Text>
                <Text style={styles.listItem}>
                • With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates 
                to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners 
                or other companies that We control or that are under common control with Us.
                </Text>
                <Text style={styles.listItem}>
                • With business partners: We may share Your information with Our business partners to offer You certain products, 
                services or promotions.
                </Text>
                <Text style={styles.listItem}>
                • With other users: when You share personal information or otherwise interact in the public areas with other users, 
                such information may be viewed by all users and may be publicly distributed outside.
                </Text>
                <Text style={styles.listItem}>
                • With Your consent: We may disclose Your personal information for any other purpose with Your consent.
                </Text>
            </View>

            {/* Retention of Your Personal Data */}
            <View style={styles.section}>
                <Text style={styles.subheading}>Retention of Your Personal Data</Text>
                <Text style={styles.paragraph}>
                The Company will retain Your Personal Data only for as long as is necessary for the
                purposes set out in this Privacy Policy. We will retain and use Your Personal Data
                to the extent necessary to comply with our legal obligations, resolve disputes, and
                enforce our legal agreements and policies.
                </Text>
            </View>

            {/* Transfer of Your Personal Data */}
            <View style={styles.section}>
                <Text style={styles.subheading}>Transfer of Your Personal Data</Text>
                <Text style={styles.paragraph}>
                Your information, including Personal Data, is processed at the Company's operating
                offices and in any other places where the parties involved in the processing are
                located. It means that this information may be transferred to — and maintained on —
                computers located outside of Your state, province, country, or other governmental
                jurisdiction where the data protection laws may differ from those in Your
                jurisdiction.
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.subheading}>Delete Your Personal Data</Text>
                <Text style={styles.paragraph}>
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
                Our Service may give You the ability to delete certain information about You from within the Service.
                You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
                Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.subheading}>Disclosure of Your Personal Data</Text>
                <Text style={styles.paragraph}>
                    <Text style={styles.bold}>Business Transactions</Text>
                    {"\n"}If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. 
                    We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </Text>
                <Text style={styles.paragraph}>
                    <Text style={styles.bold}>Law enforcement</Text>
                    {"\n"}Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by 
                    law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </Text>
                <Text style={styles.paragraph}>
                    <Text style={styles.bold}>Other legal requirements</Text>
                    {"\n"}The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </Text>
                <Text style={styles.listItem}>
                • Comply with a legal obligation
                </Text>
                <Text style={styles.listItem}>
                • Protect and defend the rights or property of the Company
                </Text>
                <Text style={styles.listItem}>
                • Prevent or investigate possible wrongdoing in connection with the Service
                </Text>
                <Text style={styles.listItem}>
                • Protect the personal safety of Users of the Service or the public
                </Text>
                <Text style={styles.listItem}>
                • Protect against legal liability
                </Text>   
            </View>

            <View style={styles.section}>
                <Text style={styles.subheading}>Security of Your Personal Data</Text>
                <Text style={styles.paragraph}>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. 
                While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.heading}>Children's Privacy</Text>
                <Text style={styles.paragraph}>
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. 
                If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. 
                If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.heading}>Links to Other Websites</Text>
                <Text style={styles.paragraph}>
                Our Service may contain links to other websites that are not operated by Us. 
                If You click on a third party link, You will be directed to that third party's site. 
                We strongly advise You to review the Privacy Policy of every site You visit.
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.heading}>Changes to this Privacy Policy</Text>
                <Text style={styles.paragraph}>
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </Text>
            </View>

            <Text style={styles.heading}>Contact Us</Text>
            <Text style={styles.paragraph}>
                If you have any questions about this Privacy Policy, You can contact us:
            </Text>
            <Text style={styles.paragraph}>By email: brandonlee04284@gmail.com</Text>
            <View style={styles.footer}></View>
        </ScrollView>
        </View>

    );
};

const getResponsiveFontSize = (baseFontSize) => {
    const scale = width / 425;
    return Math.round(baseFontSize * scale);
};

const createStyles = (theme) => StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 20,
        backgroundColor: theme.backgroundColor,
        paddingTop: height > 850 ? 60 : 50,
    },
    scrollContainer: {
    },
    backIcon: {
        marginBottom: 10
    },
    title: {
        //marginTop: 35,
        marginBottom: 8,
        fontSize: getResponsiveFontSize(26),
        color: theme.textColor,
        fontFamily: theme.fontExtraBold, 
    },
    heading: {
        //marginTop: 35,
        marginBottom: 8,
        fontSize: getResponsiveFontSize(26),
        color: theme.textColor,
        fontFamily: theme.fontBold, 
    },
    section: {
        marginBottom: 16,
    },
    subheading: {
        fontSize: getResponsiveFontSize(20),
        color: theme.textColor,
        fontFamily: theme.fontSemiBold, 
        marginVertical: 8,
    },
    subtext: {
        fontSize: getResponsiveFontSize(14),
        color: theme.textColor,
        fontFamily: theme.fontLight, 
        marginBottom: 16,
    },
    paragraph: {
        fontSize: getResponsiveFontSize(16),
        color: theme.textColor,
        fontFamily: theme.fontRegular, 
        lineHeight: getResponsiveFontSize(24),
        marginBottom: 12,
    },
    list: {
        paddingLeft: 16,
        marginBottom: 16,
    },
    listItem: {
        fontSize: getResponsiveFontSize(16),
        color: theme.textColor,
        fontFamily: theme.fontRegular, 
        lineHeight: getResponsiveFontSize(24),
        marginBottom: 8,
    },
    bold: {
        fontFamily: theme.fontBold, 
    },
    footer: {
        paddingBottom: 50
    }
});

export default PrivacyPolicyScreen;